spring:
  datasource:
    #type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    driver-class-name: oracle.jdbc.OracleDriver
    password: 1105915292
    username: liubin_test
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化sql
    #initialization-mode: always
    #continue-on-error: false
    #platform: oracle
    #schema:
    #- classpath:schema-oracle.sql

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jpa:
    #显示sql日志
    show-sql: true
#分页数据库类型
pagehelper:
  helper-dialect: oracle
  #<!-- 该参数默认为false -->
  #<!-- 设置为true时，会将RowBounds第一个参数offset当成pageNum页码使用 -->
  #<!-- 和startPage中的pageNum效果一样-->
  offset-as-page-num: true
  row-bounds-with-count: true
  #设置为true时，如果pageSize=0或者RowBounds.limit = 0就会查询出全部的结果
  page-size-zero: true

mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
  type-aliases-package: com.luki.pojo
  configuration:
    #驼峰映射
    map-underscore-to-camel-case: true
    #开启缓存
    cache-enabled: false
logging:
  file:
    name: E:/log/spingBoot.log
  level:
    com.luki.dao: debug
    root: info
    web: info


